name: Test Execution and Ketryx Reporting

on:
  push:
    branches: [ main ] # Runs every time code is pushed to the main branch
  workflow_dispatch:  # <--- This is the complete line needed

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 1: Run the test script and output a report (e.g., in a temporary file)
      - name: Execute Test
        id: test_run
        # We run the test, but the job MUST NOT fail here, 
        # so the subsequent Ketryx reporting step can run.
        run: |
          python run_test.py
        continue-on-error: true # Important: Allows the workflow to continue to the reporting step

      # Step C: Report Results to Ketryx (FINAL CORRECTION)
      - name: Report Test Execution to Ketryx
        # Make sure this uses the correct path/version you found (e.g., @v2)
        uses: Ketryx/ketryx-github-action@v1 
        with:
          # --- Authentication and Project ID ---
          project: ${{ secrets.KETRYX_PROJECT_ID }} # Corrected parameter name
          api-key: ${{ secrets.KETRYX_API_TOKEN }}    # Corrected parameter name
          
          # --- Test Results Path ---
          # This replaces 'test-results-file' and defines the path for the JUnit XML report.
          test-junit-path: ./test_results.xml

          # --- Traceability ---
          commit-sha: ${{ github.sha }}
          
          # --- REMOVED OBSOLETE PARAMETERS ---
          # 'test-results-file' is removed.
          # 'test-framework' is removed.
          
      - name: Finalize Report
        # This step ensures the workflow fails if the test failed, regardless of the reporting status
        if: ${{ steps.test_run.outcome == 'failure' }}
        run: exit 1
